name: CD-auto

on:
  pull_request:
    types:
      - closed
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  cd:
    uses: mihaigalos/config/.github/workflows/rust-cd-auto.yaml@main
    secrets:
      CARGO_API_KEY: ${{ secrets.CARGO_API_KEY }}

